/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Resultado.java
 *
 * Created on 25/08/2011, 14:27:34
 */
package view;

import model.Subject;
import model.model;

/**
 *
 * @author vinicius.rodrigues
 */
public class resultado extends javax.swing.JFrame implements Observer {

    private model dados;
    /** Creates new form Resultado */
    public resultado(model m) {
        initComponents();
        this.dados = m;
        dados.addObserver(this);
        inicializa();
    }
    
    private void inicializa(){
        this.setTitle("Resultado");
        this.jLabel1.setText("-");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Subject o) {
        String n1 = dados.getNum1().toString();
        String n2 = dados.getNum2().toString();
        String re = dados.getResult().toString();
        String op = dados.getOperacao();
        this.jLabel1.setText(n1 + " " + op + " " + n2 + " = " + re);
    }
}
